# Generated by Django 4.2.1 on 2023-05-18 14:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ducks', '0007_duckrate'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='fav_ducks',
            field=models.ManyToManyField(to='ducks.duck'),
        ),
        migrations.AddField(
            model_name='account',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
