# Generated by Django 4.2.1 on 2023-05-14 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ducks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='duck',
            name='avg_height',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='duck',
            name='avg_weight',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=3, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
