# Generated by Django 4.2.1 on 2023-05-14 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ducks', '0002_duck_avg_height_duck_avg_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='duck',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
