# Generated by Django 4.2.1 on 2023-05-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ducks', '0004_remove_duck_avg_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duck',
            name='occupied_areas',
        ),
        migrations.AddField(
            model_name='duck',
            name='origin_country',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
