# Generated by Django 4.2.1 on 2023-05-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ducks', '0005_remove_duck_occupied_areas_duck_origin_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duck',
            name='origin_country',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
